services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    volumes:
      - ./docker/mssql/data:/var/opt/mssql/data
      - ./docker/mssql/log:/var/opt/mssql/log
      - ./docker/mssql/secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
      - MSSQL_PID=Developer
        
        
       